### PR TITLE
No more WW3 over civil wars in shitholes

### PR DESCRIPTION
**Pull request by JagerCafeHold**
this should stop annoying ass civil war spam >1945

### CODE REVIEW

**Comment by uncharted85** [comment]
We need to actually improve the AI so they dont go into such deficits of stab and war support

**Comment by Ethan156** [comment]
So now the AI of south american countries and other minors (like Oman and Yemen) don't go above civ eco and limited conscription right?

**Comment by JagerCafeHold** [comment]
> So now the AI of south american countries and other minors (like Oman and Yemen) don't go above civ eco and limited conscription right?

yes

**Comment by Ethan156** [comment]
Maybe make it to where if they are in a war they can change these laws? Otherwise players can walk right through

**Comment by Ethan156** [comment]
> > Maybe make it to where if they are in a war they can change these laws? Otherwise players can walk right through
> 
> some of them will join the allies make 1 division and go on scraping the barrel which causes a civil war lategame

Can we make it to where it only happens on defensive wars? has_defensive_war = yes. Just to prevent being able to cheese cap all these countries without any sort of fight

**Pull request closed without merging**
